version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=phonebooking
      - POSTGRES_USER=phonebooking
      - POSTGRES_PASSWORD=phonebooking
    ports:
      - "5432:5432"
  phone-booking:
    image: timurnav/phone-booking:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/phonebooking
    depends_on:
      - postgres
